config/routes.rb
Rails.application.routes.draw do
resources :castles
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
    get "mypage", :to => "users#mypage"
    get "mypage/edit", :to => "users#edit"
    put "mypage", :to => "users#update"
   end
  end
end

app/models/castle.rb
class Castle < ApplicationRecord
   enum prefectures_area:{ "---":0,
   北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
   茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
   新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
   岐阜県:21,静岡県:22,愛知県:23,三重県:24,
   滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
   鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
   徳島県:36,香川県:37,愛媛県:38,高知県:39,
   福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
   沖縄県:47 }, _prefix: true
   enum region_area:{ "---":0,北海道地方:1,東北地方:2,関東地方:3,東海地方:1,中部地方:1,近畿地方:2,中国地方:3,四国地方:3,九州地方:3,沖縄地方:3 }, _prefix: true
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  def index
    @castles = Castle.all
    @user = current_user
  end

  def show
    @castle = Castle.find(params[:id])
  end

  def new
    @castle = Castle.new
  end

  def create
    @castle = Castle.new(castle_params)
    @castle.save
    redirect_to castle_url @castle

  end

  def edit
    @castle = Castle.find(params[:id])
  end

  def update
    @castle = Castle.find(params[:id])
    @castle.update(castle_params)
    redirect_to castle_url @castle
  end

  def destroy
    @castle = Castle.find(params[:id])
    @castle.destroy
    redirect_to castles_url
  end
  
  private
  def castle_params
    params.require(:castle).permit( :name, :content, :region, :prefectures, :lord, :construction_year, :image, :created_at, :updated_at, :prefectures_area, :region_area)
  end
end

app/helpers/castles_helper.rb
module CastlesHelper
end

app/views/castles/create.html.erb
<h1>Castles#create</h1>
<p>Find me in app/views/castles/create.html.erb</p>

app/views/castles/destroy.html.erb
<h1>Castles#destroy</h1>
<p>Find me in app/views/castles/destroy.html.erb</p>

app/views/castles/edit.html.erb
 <h1>Update Castles</h1>
 
<%= form_with model: @castle do |f| %>
<div class="card mb-3" style="max-width: 1580px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." alt="...">
    </div>
    
        <div class="card-body">
            
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "城名", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :name, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "通称・別名", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :content, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "地方", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.select :region_area, Castle.region_areas.keys, {} , class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "都道府県", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.select :prefectures, Castle.prefectures_areas.keys, {} , class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "城主", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :lord, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "築城年", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :construction_year, class: 'form-control'%>
            </div>
         </div>
        </div>
        
       <%= f.submit "Update" %>
       
      </div>
    </div>
  </div>
</div>

<% end %>
 
 <%= link_to "Back", castles_path %>

app/views/castles/index.html.erb
<h1>Castles#index</h1>
 <% @castles.each do |castle| %>
   <%= castle.name %>
   <%= castle.content %>
   <%= castle.region_area %>
   <%= castle.prefectures %>
   <%= castle.lord %> s
   <%= castle.construction_year %>
   <%= castle.image %>
    <% if @user.admin == true %>
     <%= link_to "Show", castle_path(castle) %>
     <%= link_to "Edit", edit_castle_path(castle) %>
     <%= link_to "Delete", castle_path(castle), method: :delete, data: { confirm: 'Are you sure?' }  %>
     <%= link_to "New", new_castle_path %>
    <% else %>
     <%= link_to "Show", castle_path(castle) %>
    <% end %>
  <% end %>
  

app/views/castles/new.html.erb
<h1>新規城登録</h1>

<%= form_with model: @castle do |f| %>
<div class="card mb-3" style="max-width: 1580px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." alt="...">
    </div>
    
        <div class="card-body">
            
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "城名", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :name, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "通称・別名", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :content, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "地方", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.select :region_area, Castle.region_areas.keys, {} , class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "都道府県", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.select :prefectures_area, Castle.prefectures_areas.keys, {} , class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "城主", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :lord, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "築城年", class: "col-sm-2 col-form-label"%><br/>
            <div class="col-sm-10">
              <%= f.text_field :construction_year, class: 'form-control'%>
            </div>
         </div>
        </div>
        
        <%= f.submit "Create" %>

      </div>
    </div>
  </div>
</div>

<% end %>
 
<%= link_to "Back", castles_path %>

app/views/castles/show.html.erb
<h1>城の一覧</h1>

<%= form_with model: @castle do |f| %>
<div class="card mb-3" style="max-width: 1580px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." alt="...">
    </div>
    
        <div class="card-body">
    
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "城名", class: "col-sm-2 col-form-label"%><br/>
            <%= f.label @castle.name, class: "col-sm-10 col-form-label"%>
         </div>
        </div>

        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "通称・別名", class: "col-sm-2 col-form-label"%><br/>
            <%= f.label @castle.content, class: "col-sm-10 col-form-label"%>
         </div>
        </div>     

        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "地方", class: "col-sm-2 col-form-label"%><br/>
            <%= f.label @castle.region_area, class: "col-sm-10 col-form-label"%>
         </div>
        </div>
      
        
        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "城主", class: "col-sm-2 col-form-label"%><br/>
            <%= f.label @castle.lord, class: "col-sm-10 col-form-label"%>
         </div>
        </div>

        <div class="col-md-8">
         <div class="form-group row">
            <%= f.label "築城年", class: "col-sm-2 col-form-label"%><br/>
            <%= f.label @castle.construction_year, class: "col-sm-10 col-form-label"%>
         </div>
        </div>
   
      </div>
    </div>
  </div>
</div>

<% end %>
 
 <%= link_to "Back", castles_path %>

app/views/castles/update.html.erb
<h1>Castles#update</h1>
<p>Find me in app/views/castles/update.html.erb</p>