config/routes.rb
Rails.application.routes.draw do
resources :castles
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "users/sessions#new"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
    get "mypage", :to => "users#mypage"
    get "mypage/edit", :to => "users#edit"
    put "mypage", :to => "users#update"
   end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="fixed-top mt-5 container">
    <div class="alert <%= bs4_bgcolor_for(key) %> alert-dismissable fade show my-3">
      <%= value %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light d-flex flex-column justify-content-end align-items-end">
  <div class="text-muted small px-3">CASTLE App by Ruby on Rails & Bootstrap 4</div>
</footer>

app/views/layouts/_header.html.erb
<header
  <div class="d-flex flex-column bd-highlight mb-3">
  <div class="p-2 bd-highlight">
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm castle-header-container">
    <%= link_to root_path do %>
      <%= image_tag "/images/castle_logo.jpg" %>
    <% end %>
    <form class="form-inline">
      <div class="form-group">
        <input class="form-control castle-header-search-input">
      </div>
      <div class="input-group">
        <button type="submit" class="btn castle-header-search-button"><i class="fas fa-search castle-header-search-icon"></i></button>
      </div>
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-5 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <li class="nav-item mr-5">
          <%= link_to mypage_users_path, class: "nav-link" do %>
            <i class="fas fa-user mr-1"></i><label>マイページ</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to root_path, class: "nav-link" do %>
            <label>ログアウト</label>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item mr-5">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <label>新規登録</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログアウト</label>
          <% end %>
        </li>
        <hr>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="far fa-heart"></i><% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="fas fa-shopping-cart"></i><% end %>
        </li>
        <% end %>
     
    </div>
      </div
   <div class="d-flex justify-content-center">
     <div class="header_mypage_topimage">
        <img src="/assets/Matsumoto Castle_Pagetop.jpg" />
        <div class="header-cover__actions">
          <p class="btn-setting">
            <a class="c-btn c-btn--s" onclick="onclickcatalystbutton('mypage_edit_button')" href="/users/mypage/edit">マイページ設定</a>
          </p>
       </div>
      </div>
     </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Castle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8aeca36c69.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <main class="py-4 mb-5">
      <% if notice %><p class="alert alert-warning"><%= notice %></div><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
      <%= yield %>
    </main>
  </body>
</html>